config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  resources :reservations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/field.rb
class Field < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :prepaid, presence: true
  validates :date, presence: true, inclusion: { in: (Date.today..Date.today+5.years) }
  validates :hour, presence: true
  validates_uniqueness_of :hour, scope: :date

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(article_params)

    if @reservation.save
      redirect_to @reservation
    else
      render :new
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(article_params)
      redirect_to @reservation
    else
      render :edit
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_path
  end

  private

  def article_params
    params.require(:reservation).permit(:date, :prepaid, :hour)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CanchitaYa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="headBar">

        <div class="logo white">
          <h1>CanchitaYa!</h1>
        </div>
        <div class="search">
          <label class="white question" for="inputHelpBlock">En qué localidad querés jugar?</label>
          <input id="input-search" class="form-control" type="text" name="search">
          <button class="btn btn-default">search</button>
        </div>
        <p class="white subtitle">Consigue tu cancha en segundos...</p>
      </nav>
    </header>
    <div class="container">
      <%= yield %>
    <div>
  </body>
</html>

app/views/reservations/_form.html.erb
<h1><%= name %> reserva</h1>

<%= form_for(@reservation) do |f| %>
<div class="form-group">
  <% @reservation.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message%>
    </div>
  <%end%>
  <label for="article_title">Fecha:</label>
   <%= f.date_field :date, class: 'form-control' %>
 </div>
 <div class="form-group">
  <label for="article_body">Hora</label>
   <%= f.number_field :hour, class: 'form-control' %>
 </div>
 <div class="form-group">
  <label for="article_body">Seña</label>
   <%= f.number_field :prepaid, class: 'form-control' %>
 </div>
 <%= f.submit name , class: 'btn btn-primary' %>
 <%= link_to "Cancelar", reservations_path, class: 'btn btn-primary' %>
<%end%>

app/views/reservations/edit.html.erb
<%= render "form", name: "Editar"%>

app/views/reservations/index.html.erb
<h1>Todas las reservas</h1>

<%= link_to "Crear Reserva", new_reservation_path, class: 'btn btn-success' %>

<table class="table">
  <thead>
    <tr>
      <th>Nro de Reserva</th>
      <th>Seña</th>
      <th>Dia</th>
      <th>Horario</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  <% @reservations.each do |reservation| %>
  <tr>
    <th><%= reservation.id %></th>
    <td>$<%= reservation.prepaid %></td>
    <td><%= reservation.date.strftime("%d/%m/%Y") %></td>
    <td><%= reservation.hour %>hs</td>
    <td class="action_buttons">
      <%= link_to "Editar", edit_reservation_path(reservation), class: 'btn btn-primary margin_action_buttons' %>
      <%= button_to "Eliminar", reservation, class: 'btn btn-danger margin_action_buttons', data: {confirm: "Está seguro que desea eliminar esta reserva?"} %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/reservations/new.html.erb
<%= render "form", name: "Crear"%>

app/views/reservations/show.html.erb
<h1> Reserva nro: <%= @reservation.id %> </h1>
Seña: <%= @reservation.prepaid %>
Dia: <%= @reservation.date %>
Horario: <%= @reservation.hour %>hs

app/views/welcome/index.html.erb
<div class="container">
  <h1>Bienvenidos a CanchitaYa!</h1>
  <p>La aplicación desarrollada para optimizar la forma en que alquilamos las canchas</p>
</div>